apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: szilard-jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: student-15
    name: in-cluster
  syncPolicy:
    automated: {}
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 13.4.6
      helm:
        valueFiles:
          - $values/jenkins/values.yaml
      chart: jenkins
    - repoURL: 'https://github.com/szilardszell/argocd-katas-training'
      targetRevision: main
      ref: values